### ISSUE TITLE
Support for releases / tags

### ISSUE THREAD

**Issue by mamccorm** [wave-k8s/wave#144]
Is there a reason that this project no longer cuts releases/tags? Looks like the last was cut back in March 2021, but images published to quay.io are based off the main branch commit

**Comment by toelke** [comment]
Basically, I took over maintaining this project after a long hiatus; I want to fix #118 before releasing the next version. To do that, we need to update a dependency. For that, I intend to migrate from `dep` to `go mod. But since much has changed since the last updates to dependencies, this is harder than I anticipated; I am on it.

**Comment by mamccorm** [comment]
Great thanks @toelke, makes sense and appreciated
